version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: omniai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omniai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  pgdata:
